version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: nutritrack_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: nutritrack_backend
    restart: always
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
      - MONGO_URI=mongodb://db:27017/nutritrack
      - JWT_SECRET=supersecretkeythatyoushouldchangeinproduction
      - GEMINI_API_KEY=$GEMINI_API_KEY
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: nutritrack_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
